package org.artbase.dao;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.artbase.database.ConnectionFactory;
import org.artbase.model.Cliente;

public class ClienteDaoJdbc {
    public void criarTabelaSeNecessario() throws SQLException, IOException, ClassNotFoundException {
        String sql = """
                CREATE TABLE IF NOT EXISTS cliente (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(120) NOT NULL,
                    cpf VARCHAR(11) NOT NULL UNIQUE,
                    telefone VARCHAR(20) NOT NULL,
                    email VARCHAR(160) NOT NULL UNIQUE,
                    endereco VARCHAR(255) NOT NULL
                )
                """;

        try (Connection connection = new ConnectionFactory().getConnection();
            Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    public Cliente salvar(Cliente cliente) throws SQLException, IOException, ClassNotFoundException {
        String sql = """
                INSERT INTO cliente (nome, cpf, telefone, email, endereco)
                VALUES (?, ?, ?, ?, ?)
                """;

        try (Connection connection = new ConnectionFactory().getConnection();
            PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, cliente.getNome());
            statement.setString(2, cliente.getCpf());
            statement.setString(3, cliente.getTelefone());
            statement.setString(4, cliente.getEmail());
            statement.setString(5, cliente.getEndereco());
            statement.executeUpdate();

            try (ResultSet keys = statement.getGeneratedKeys()) {
                if (keys.next()) {
                    return new Cliente(
                            keys.getInt(1),
                            cliente.getNome(),
                            cliente.getCpf(),
                            cliente.getTelefone(),
                            cliente.getEmail(),
                            cliente.getEndereco()
                    );
                }
            }
        }
        return cliente;
    }

    public Cliente atualizar(Cliente cliente) throws SQLException, IOException, ClassNotFoundException {
        String sql = """
                UPDATE cliente
                    SET nome = ?, cpf = ?, telefone = ?, email = ?, endereco = ?
                    WHERE id = ?
                """;

        try (Connection connection = new ConnectionFactory().getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, cliente.getNome());
            statement.setString(2, cliente.getCpf());
            statement.setString(3, cliente.getTelefone());
            statement.setString(4, cliente.getEmail());
            statement.setString(5, cliente.getEndereco());
            statement.setInt(6, cliente.getId());
            statement.executeUpdate();
        }
        return cliente;
    }

    public boolean excluir(int id) throws SQLException, IOException, ClassNotFoundException {
        String sql = "DELETE FROM cliente WHERE id = ?";

        try (Connection connection = new ConnectionFactory().getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, id);
            return statement.executeUpdate() > 0;
        }
    }

    public Cliente buscarPorId(int id) throws SQLException, IOException, ClassNotFoundException {
        String sql = "SELECT id, nome, cpf, telefone, email, endereco FROM cliente WHERE id = ?";

        try (Connection connection = new ConnectionFactory().getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, id);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new Cliente(
                            resultSet.getInt("id"),
                            resultSet.getString("nome"),
                            resultSet.getString("cpf"),
                            resultSet.getString("telefone"),
                            resultSet.getString("email"),
                            resultSet.getString("endereco")
                    );
                }
            }
        }
        return null;
    }

    public Cliente buscarPorCpf(String cpf) throws SQLException, IOException, ClassNotFoundException {
        String sql = "SELECT id, nome, cpf, telefone, email, endereco FROM cliente WHERE cpf = ?";

        try (Connection connection = new ConnectionFactory().getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, cpf);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return new Cliente(
                            resultSet.getInt("id"),
                            resultSet.getString("nome"),
                            resultSet.getString("cpf"),
                            resultSet.getString("telefone"),
                            resultSet.getString("email"),
                            resultSet.getString("endereco")
                    );
                }
            }
        }
        return null;
    }

    public List<Cliente> listarTodos() throws SQLException, IOException, ClassNotFoundException {
        List<Cliente> clientes = new ArrayList<>();
        String sql = "SELECT id, nome, cpf, telefone, email, endereco FROM cliente ORDER BY id DESC";

        try (Connection connection = new ConnectionFactory().getConnection();
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                clientes.add(new Cliente(
                        resultSet.getInt("id"),
                        resultSet.getString("nome"),
                        resultSet.getString("cpf"),
                        resultSet.getString("telefone"),
                        resultSet.getString("email"),
                        resultSet.getString("endereco")
                ));
            }
        }
        return clientes;
    }
}
