package org.artbase.dao;

import org.artbase.database.ConnectionFactory;
import org.artbase.model.Produto;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Classe responsável por toda a persistência (CRUD) da entidade Produto
 * no banco de dados PostgreSQL, seguindo o mesmo padrão de acesso via
 * JDBC utilizado em ClienteDaoJdbc: cada método abre sua própria conexão
 * através da ConnectionFactory, utilizando try-with-resources para
 * garantir o fechamento automático da conexão ao final da operação.
 */
public class ProdutoDaoJdbc {

    /**
     * Cria a tabela "produto" no banco caso ela ainda não exista.
     * É por causa dessa verificação que o sistema não quebra na primeira
     * execução em uma máquina/banco novo: sem ela, qualquer INSERT/SELECT
     * na tabela produto falharia com "relation produto does not exist".
     * As colunas seguem o diagrama de banco combinado pela equipe.
     */
    public void criarTabelaSeNecessario() throws SQLException, IOException, ClassNotFoundException {
        String sql = """
                CREATE TABLE IF NOT EXISTS produto (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(150) NOT NULL,
                    descricao TEXT,
                    preco REAL NOT NULL,
                    quantidade_disponivel SMALLINT NOT NULL DEFAULT 0,
                    estoque_minimo SMALLINT NOT NULL DEFAULT 0,
                    categoria VARCHAR(80)
                )
                """;

        try (Connection connection = new ConnectionFactory().getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    /**
     * Insere um novo produto no banco de dados.
     * Recebe um objeto Produto já preenchido (sem o id, que é gerado
     * automaticamente pelo banco) e retorna true caso a inserção
     * tenha afetado ao menos uma linha.
     */
    public boolean salvar(Produto produto) throws SQLException, IOException, ClassNotFoundException {
        String sql = """
                INSERT INTO produto (nome, descricao, preco, quantidade_disponivel, estoque_minimo, categoria)
                VALUES (?, ?, ?, ?, ?, ?)
                """;

        try (Connection conn = new ConnectionFactory().getConnection();
             PreparedStatement preparedStatement = conn.prepareStatement(sql)) {

            preparedStatement.setString(1, produto.getNome());
            preparedStatement.setString(2, produto.getDescricao());
            preparedStatement.setDouble(3, produto.getPreco());
            preparedStatement.setInt(4, produto.getQuantidadeDisponivel());
            preparedStatement.setInt(5, produto.getEstoqueMinimo());
            preparedStatement.setString(6, produto.getCategoria());

            return preparedStatement.executeUpdate() > 0;
        }
    }

    /**
     * Atualiza os dados de um produto já existente, localizando-o pelo id.
     * Retorna true caso alguma linha tenha sido efetivamente alterada.
     */
    public boolean atualizar(Produto produto) throws SQLException, IOException, ClassNotFoundException {
        String sql = """
                UPDATE produto
                    SET nome = ?, descricao = ?, preco = ?, quantidade_disponivel = ?, estoque_minimo = ?, categoria = ?
                    WHERE id = ?
                """;

        try (Connection conn = new ConnectionFactory().getConnection();
             PreparedStatement preparedStatement = conn.prepareStatement(sql)) {

            preparedStatement.setString(1, produto.getNome());
            preparedStatement.setString(2, produto.getDescricao());
            preparedStatement.setDouble(3, produto.getPreco());
            preparedStatement.setInt(4, produto.getQuantidadeDisponivel());
            preparedStatement.setInt(5, produto.getEstoqueMinimo());
            preparedStatement.setString(6, produto.getCategoria());
            preparedStatement.setInt(7, produto.getId());

            return preparedStatement.executeUpdate() > 0;
        }
    }

    /**
     * Remove um produto do banco de dados a partir do seu id.
     * Retorna true caso o registro tenha sido encontrado e removido.
     */
    public boolean deletar(int id) throws SQLException, IOException, ClassNotFoundException {
        try (Connection conn = new ConnectionFactory().getConnection();
             PreparedStatement preparedStatement = conn.prepareStatement(
                     "DELETE FROM produto WHERE id = ?"
             )) {
            preparedStatement.setInt(1, id);
            return preparedStatement.executeUpdate() > 0;
        }
    }

    /**
     * Busca um único produto pelo seu id.
     * Retorna o objeto Produto preenchido, ou null caso nenhum registro
     * seja encontrado com o id informado.
     */
    public Produto buscarPorId(int id) throws SQLException, IOException, ClassNotFoundException {
        String sql = "SELECT id, nome, descricao, preco, quantidade_disponivel, estoque_minimo, categoria " +
                "FROM produto WHERE id = ?";

        try (Connection conn = new ConnectionFactory().getConnection();
             PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
            preparedStatement.setInt(1, id);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    return mapear(resultSet);
                }
            }
        }
        return null;
    }

    /**
     * Lista todos os produtos cadastrados no banco de dados.
     * Percorre o ResultSet inteiro, montando um objeto Produto para
     * cada linha retornada e adicionando-o à lista de resultado.
     */
    public List<Produto> listarTodos() throws SQLException, IOException, ClassNotFoundException {
        List<Produto> produtos = new ArrayList<>();
        String sql = "SELECT id, nome, descricao, preco, quantidade_disponivel, estoque_minimo, categoria " +
                "FROM produto ORDER BY nome";

        try (Connection conn = new ConnectionFactory().getConnection();
             PreparedStatement preparedStatement = conn.prepareStatement(sql);
             ResultSet resultSet = preparedStatement.executeQuery()) {

            while (resultSet.next()) {
                produtos.add(mapear(resultSet));
            }
        }
        return produtos;
    }

    /**
     * Converte a linha atual de um ResultSet em um objeto Produto,
     * evitando repetir esse mapeamento em buscarPorId e listarTodos.
     */
    private Produto mapear(ResultSet resultSet) throws SQLException {
        return new Produto(
                resultSet.getInt("id"),
                resultSet.getString("nome"),
                resultSet.getString("descricao"),
                resultSet.getDouble("preco"),
                resultSet.getInt("quantidade_disponivel"),
                resultSet.getInt("estoque_minimo"),
                resultSet.getString("categoria")
        );
    }
}
