package org.artbase.dao;

import org.artbase.database.ConnectionFactory;
import org.artbase.model.ItemVenda;
import org.artbase.model.Venda;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Classe responsável pela persistência das entidades Venda e ItemVenda.
 * A operação principal (registrarVenda) insere a venda, todos os seus
 * itens e dá baixa no estoque de cada produto dentro de uma única
 * transação: se qualquer passo falhar (ex: estoque insuficiente), tudo
 * é desfeito com ROLLBACK, evitando vendas "pela metade" no banco.
 */
public class VendaDaoJdbc {

    /**
     * Cria as tabelas "venda" e "item_venda" caso ainda não existam.
     * A tabela venda precisa existir antes de item_venda, já que
     * item_venda referencia venda através de uma foreign key.
     */
    public void criarTabelaSeNecessario() throws SQLException, IOException, ClassNotFoundException {
        String sqlVenda = """
                CREATE TABLE IF NOT EXISTS venda (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data_da_venda DATE NOT NULL DEFAULT CURRENT_DATE,
                    cliente INTEGER NOT NULL REFERENCES cliente(id),
                    valor_total DOUBLE PRECISION NOT NULL,
                    forma_de_pagamento VARCHAR(40) NOT NULL,
                    situacao_da_venda VARCHAR(30) NOT NULL DEFAULT 'CONCLUIDA'
                )
                """;

        String sqlItemVenda = """
                CREATE TABLE IF NOT EXISTS item_venda (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    venda_id INTEGER NOT NULL REFERENCES venda(id),
                    produto_id INTEGER NOT NULL REFERENCES produto(id),
                    quantidade INTEGER NOT NULL,
                    preco_unitario DOUBLE PRECISION NOT NULL,
                    subtotal DOUBLE PRECISION NOT NULL
                )
                """;

        try (Connection connection = new ConnectionFactory().getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sqlVenda);
            statement.execute(sqlItemVenda);
        }
    }

    /**
     * Registra uma venda completa: insere a linha em "venda", insere uma
     * linha em "item_venda" para cada item e desconta a quantidade
     * vendida do estoque de cada produto. Tudo dentro de uma transação:
     * se um produto não tiver estoque suficiente no momento de confirmar,
     * a venda inteira é cancelada (ROLLBACK) e nada fica salvo.
     */
    public Venda registrarVenda(Venda venda, List<ItemVenda> itens)
            throws SQLException, IOException, ClassNotFoundException {

        String sqlVenda = """
                INSERT INTO venda (data_da_venda, cliente, valor_total, forma_de_pagamento, situacao_da_venda)
                VALUES (?, ?, ?, ?, ?)
                """;
        String sqlItem = """
                INSERT INTO item_venda (venda_id, produto_id, quantidade, preco_unitario, subtotal)
                VALUES (?, ?, ?, ?, ?)
                """;
        // Só desconta o estoque se ele realmente comportar a quantidade vendida;
        // se 0 linhas forem afetadas, é sinal de estoque insuficiente.
        String sqlBaixaEstoque = """
                UPDATE produto SET quantidade_disponivel = quantidade_disponivel - ?
                    WHERE id = ? AND quantidade_disponivel >= ?
                """;

        try (Connection connection = new ConnectionFactory().getConnection()) {
            connection.setAutoCommit(false);

            try (PreparedStatement stmtVenda = connection.prepareStatement(sqlVenda, Statement.RETURN_GENERATED_KEYS);
                 PreparedStatement stmtItem = connection.prepareStatement(sqlItem);
                 PreparedStatement stmtEstoque = connection.prepareStatement(sqlBaixaEstoque)) {

                stmtVenda.setDate(1, Date.valueOf(venda.getDataDaVenda()));
                stmtVenda.setInt(2, venda.getClienteId());
                stmtVenda.setDouble(3, venda.getValorTotal());
                stmtVenda.setString(4, venda.getFormaDePagamento());
                stmtVenda.setString(5, venda.getSituacaoDaVenda());
                stmtVenda.executeUpdate();

                int vendaId;
                try (ResultSet keys = stmtVenda.getGeneratedKeys()) {
                    keys.next();
                    vendaId = keys.getInt(1);
                }

                for (ItemVenda item : itens) {
                    stmtEstoque.setInt(1, item.getQuantidade());
                    stmtEstoque.setInt(2, item.getProdutoId());
                    stmtEstoque.setInt(3, item.getQuantidade());
                    int linhasAfetadas = stmtEstoque.executeUpdate();
                    if (linhasAfetadas == 0) {
                        throw new IllegalStateException(
                                "Estoque insuficiente para o produto \"" + item.getProdutoNome() + "\".");
                    }

                    stmtItem.setInt(1, vendaId);
                    stmtItem.setInt(2, item.getProdutoId());
                    stmtItem.setInt(3, item.getQuantidade());
                    stmtItem.setDouble(4, item.getPrecoUnitario());
                    stmtItem.setDouble(5, item.getSubtotal());
                    stmtItem.executeUpdate();
                }

                connection.commit();
                venda.setId(vendaId);
                return venda;

            } catch (SQLException | IllegalStateException ex) {
                connection.rollback();
                throw ex;
            } finally {
                connection.setAutoCommit(true);
            }
        }
    }

    /**
     * Lista todas as vendas já registradas, já trazendo o nome do
     * cliente (via JOIN) para facilitar a exibição em tabela.
     */
    public List<Venda> listarTodas() throws SQLException, IOException, ClassNotFoundException {
        List<Venda> vendas = new ArrayList<>();
        String sql = """
                SELECT v.id, v.data_da_venda, v.cliente, v.valor_total, v.forma_de_pagamento, v.situacao_da_venda,
                       c.nome AS cliente_nome
                FROM venda v
                JOIN cliente c ON c.id = v.cliente
                ORDER BY v.id DESC
                """;

        try (Connection connection = new ConnectionFactory().getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {

            while (resultSet.next()) {
                Venda venda = new Venda(
                        resultSet.getInt("id"),
                        resultSet.getDate("data_da_venda").toLocalDate(),
                        resultSet.getInt("cliente"),
                        resultSet.getDouble("valor_total"),
                        resultSet.getString("forma_de_pagamento"),
                        resultSet.getString("situacao_da_venda")
                );
                venda.setClienteNome(resultSet.getString("cliente_nome"));
                vendas.add(venda);
            }
        }
        return vendas;
    }
}
